apiVersion: v1
kind: Secret
metadata:
  name: fraud-detection-secrets
  namespace: fraud-detection
type: Opaque
stringData:
  SECRET_KEY: "your-secret-key-here"
  JWT_SECRET_KEY: "your-jwt-secret-here"
  ADMIN_PASSWORD: "your-admin-password-here"
  DATABASE_PASSWORD: "fraud_password"